name: Netlify Deployment Status

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Pending Deployment Status
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
               -d '{"state": "pending", "target_url": "https://mindfullweb.netlify.app/", "description": "Deployment in progress", "context": "Netlify"}'

      - name: Deploy to Netlify
        run: echo "Deploying to Netlify..." # Replace this with your actual Netlify deployment script

      - name: Set Success Deployment Status
        if: success()
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
               -d '{"state": "success", "target_url": "https://mindfullweb.netlify.app/", "description": "Deployment successful", "context": "Netlify"}'

      - name: Set Failure Deployment Status
        if: failure()
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
               -d '{"state": "failure", "target_url": "https://mindfullweb.netlify.app/", "description": "Deployment failed", "context": "Netlify"}'
